"""
Functions/commands signatures, insn mappings, etc.
"""

class Signature:
    def __init__(self, name, insn, signature):
        self.name = name
        self.insn = insn
        self.signature = signature
        
    def __format__(self, _unused):
        return f"{self.name}({', '.join(self.signature)})"
        
COMMAND_SIGNATURES = [
	Signature("turnTowardX", "TurnTowardX", ["int16", "eval"]),
	Signature("turnTowardY", "TurnTowardY", ["int16", "eval"]),
	Signature("turnTowardWaypointX", "TurnTowardWaypointX", ["eval"]),
	Signature("playSound", "PlaySound", ["int8", "eval", "varargs"]),
	Signature("stopSound", "StopSound", ["eval"]),
	Signature("playAnim", "PlayAnim", ["eval"]),
	Signature("stopAnim", "StopAnim", []),
	Signature("waitAnimend", "WaitAnimend", []),
	Signature("print", "Print", ["string"]),
	Signature("specialFXOn", "SpecialFXOn", ["eval"]),
	Signature("wait", "Wait", ["eval"]),
	Signature("resetPosition", "ResetPosition", []),
	Signature("scaleX", "ScaleX", ["eval"]),
	Signature("scaleY", "ScaleY", ["eval"]),
	Signature("scaleZ", "ScaleZ", ["eval"]),
	Signature("jump", "Jump", ["eval"]),
	Signature("fall", "Fall", []),
	Signature("moveBackward", "MoveBackward", ["eval"]),
	Signature("moveForward", "MoveForward", ["eval"]),
	Signature("moveRight", "MoveRight", ["eval"]),
	Signature("moveDown", "MoveDown", ["eval"]),
	Signature("moveLeft", "MoveLeft", ["eval"]),
	Signature("moveUp", "MoveUp", ["eval"]),
	Signature("turnRight", "TurnRight", ["eval"]),
	Signature("turnLeft", "TurnLeft", ["eval"]),
	Signature("tiltBackward", "TiltBackward", ["eval"]),
	Signature("tiltForward", "TiltForward", ["eval"]),
	Signature("tiltRight", "TiltRight", ["eval"]),
	Signature("tiltLeft", "TiltLeft", ["eval"]),
	Signature("spawn", "Spawn", ["int8", "string", "varargs"]),
	Signature("createTrigger", "CreateTrigger", ["int8", "varargs", "trigger"]),
	Signature("killTrigger", "KillTrigger", ["int16"]),
	Signature("letGVar", "LetGVar", ["int16", "eval"]),
    Signature("remove", "Remove", []),
	Signature("letPGVar", "LetPGVar", ["int16", "eval"]),
	Signature("letAVar", "LetAVar", ["int16", "eval"]),
	Signature("setModel", "SetModel", ["eval"]),
	Signature("blink", "Blink", ["int8", "varargs_int"]),
	Signature("holdTrigger", "HoldTrigger", []),
	Signature("releaseTrigger", "ReleaseTrigger", []),
	Signature("setAnim", "SetAnim", ["eval"]),
	Signature("turnTowardXY", "TurnTowardXY", ["int16", "eval", "eval"]),
	Signature("hold", "Hold", []),
	Signature("release", "Release", ["string"]),
	Signature("inc", "Inc", ["int8", "int16"]),
	Signature("playerAttackOn", "PlayerAttackOn", []),
	Signature("playerAttackOff", "PlayerAttackOff", []),
	Signature("camWobble", "CamWobble", ["eval"]),
	Signature("lookAtMe_0", "LookAtMe_0", []),
	Signature("shadowSize", "ShadowSize", ["eval"]),
	Signature("shadowType", "ShadowType", ["int8"]),
	Signature("clearAnim", "ClearAnim", []),
	Signature("stopFall", "StopFall", []),
	Signature("setPlayerPosRel", "SetPlayerPosRel", ["eval", "eval", "eval"]),
	Signature("collectKey", "CollectKey", []),
	Signature("removeKey", "RemoveKey", []),
	Signature("collisionOn", "CollisionOn", ["eval"]),
	Signature("collisionOff", "CollisionOff", ["eval"]),
	Signature("pauseTriggers", "PauseTriggers", []),
	Signature("unpauseTriggers", "UnpauseTriggers", []),
	Signature("setPosition", "SetPosition", []),
	Signature("isPlayer", "IsPlayer", []),
	Signature("scale", "Scale", ["eval"]),
	Signature("turnTowardWaypointY", "TurnTowardWaypointY", ["eval"]),
	Signature("hide", "Hide", []),
	Signature("unhide", "Unhide", []),
	Signature("letXGVar", "LetXGVar", ["int16", "eval"]),
	Signature("setCamHeight", "SetCamHeight", ["eval"]),
	Signature("setLevel", "SetLevel", ["eval", "eval"]),
	Signature("shadowOn", "ShadowOn", []),
	Signature("shadowOff", "ShadowOff", []),
	Signature("accelerate", "Accelerate", []),
	Signature("decelerate", "Decelerate", []),
	Signature("setAnimSpeed", "SetAnimSpeed", ["eval"]),
	Signature("setCamDist", "SetCamDist", ["eval"]),
	Signature("userTrigger", "UserTrigger", ["int16", "eval"]),
	Signature("waitEvent", "WaitEvent", ["int8"]),
	Signature("playerCollisionOn", "PlayerCollisionOn", []),
	Signature("animCtrlSpdOn", "AnimCtrlSpdOn", []),
	Signature("animCtrlSpdOff", "AnimCtrlSpdOff", []),
	Signature("letParam", "LetParam", ["int16", "eval"]),
	Signature("turnTowardPosX", "TurnTowardPosX", ["eval", "eval", "eval", "eval"]),
	Signature("specialFXOff", "SpecialFXOff", ["eval"]),
	Signature("openEyes", "OpenEyes", []),
	Signature("closeEyes", "CloseEyes", ["int8", "varargs_int"]),
	Signature("jumpCtrlOn", "JumpCtrlOn", []),
	Signature("jumpCtrlOff", "JumpCtrlOff", []),
	Signature("stomp", "Stomp", []),
	Signature("pushCamera", "PushCamera", []),
	Signature("pullCamera", "PullCamera", []),
	Signature("float", "Float", []),
	Signature("spawnChild", "SpawnChild", ["int8", "string", "varargs"]), # Warning: Variable arguments, cannot yet properly disassemble
	Signature("setCamera", "SetCamera", ["eval"]),
	Signature("addPickup", "AddPickup", ["eval"]),
	Signature("losePickups", "LosePickups", []),
	Signature("reverse", "Reverse", []),
	Signature("playerCollisionOff", "PlayerCollisionOff", []),
	Signature("setCollPoint", "SetCollPoint", ["eval", "eval", "eval", "eval"]),
	Signature("setCollPoints", "SetCollPoints", ["eval"]),
	Signature("pushingOn", "PushingOn", []),
	Signature("pushingOff", "PushingOff", []),
	Signature("pushableOn", "PushableOn", []),
	Signature("pushableOff", "PushableOff", []),
	Signature("pushWaypoint", "PushWaypoint", []),
	Signature("pullWaypoint", "PullWaypoint", []),
	Signature("nextWaypoint", "NextWaypoint", []),
	Signature("prevWaypoint", "PrevWaypoint", []),
	Signature("turnTowardWaypointXY", "TurnTowardWaypointXY", ["eval", "eval"]),
	Signature("turnTowardPosXY", "TurnTowardPosXY", ["eval", "eval", "eval", "eval", "eval"]),
	Signature("nearestWaypointNext", "NearestWaypointNext", []),
	Signature("nearestWaypointPrev", "NearestWaypointPrev", []),
	Signature("deleteWaypoint", "DeleteWaypoint", []),
	Signature("moveForwardAngle", "MoveForwardAngle", ["eval", "eval"]),
	Signature("turnTowardPosY", "TurnTowardPosY", ["eval", "eval", "eval", "eval"]),
	Signature("movePlayerForward", "MovePlayerForward", ["eval"]),
	Signature("movePlayerBackward", "MovePlayerBackward", ["eval"]),
	Signature("loopSound", "LoopSound", ["eval", "eval"]),
	Signature("wobble", "Wobble", ["int8", "int16"]),
	Signature("camHold", "CamHold", ["eval"]),
	Signature("speedUp", "SpeedUp", ["eval"]),
	Signature("slowDown", "SlowDown", ["eval"]),
	Signature("smoothSpeed", "SmoothSpeed", ["eval"]),
	Signature("accelerateAngle", "AccelerateAngle", ["eval"]),
	Signature("decelerateAngle", "DecelerateAngle", ["eval"]),
	Signature("movePosition", "MovePosition", ["int16", "int16", "int16", "eval", "eval"]),
	Signature("removeFromMap", "RemoveFromMap", []),
	Signature("initCrystal", "InitCrystal", []),
	Signature("crystal", "Crystal", []),
	Signature("endLevel", "EndLevel", []),
	Signature("stopDead", "StopDead", []),
	Signature("pitchShift", "PitchShift", ["eval", "eval"]),
	Signature("activated", "Activated", []),
	Signature("hangOn", "HangOn", []),
	Signature("hangOff", "HangOff", []),
	Signature("createDeath", "CreateDeath", []),
	Signature("doDeath", "DoDeath", []),
	Signature("endCrystal", "EndCrystal", []),
	Signature("pausePlayer", "PausePlayer", []),
	Signature("unpausePlayer", "UnpausePlayer", []),
	Signature("playerDead", "PlayerDead", []),
	Signature("slideOn", "SlideOn", []),
	Signature("slideOff", "SlideOff", []),
	Signature("firstWaypoint", "FirstWaypoint", []),
	Signature("collected", "Collected", []),
	Signature("dec", "Dec", ["int8", "int16"]),
	Signature("spawnFrom", "SpawnFrom", ["int8", "string", "varargs"]), # Warning: Variable arguments, cannot yet properly disassemble
	Signature("letXParam", "LetXParam", ["int16", "eval"]),
	Signature("removeCrystal", "RemoveCrystal", []),
	Signature("collectJigsaw", "CollectJigsaw", ["eval"]),
	Signature("bonus", "Bonus", ["int32"]),
	Signature("nextLevel", "NextLevel", []),
	Signature("lookAtMe_1", "LookAtMe_1", []),
	Signature("noHang", "NoHang", []),
	Signature("vibrate", "Vibrate", ["eval"]),
	Signature("playerNoStood", "PlayerNoStood", []),
	Signature("removeGobbo", "RemoveGobbo", []),
	Signature("pauseTriggersNoAnim", "PauseTriggersNoAnim", []),
	Signature("showBonus", "ShowBonus", []),
	Signature("lookAtMeMap", "LookAtMeMap", []),
	Signature("playerMove", "PlayerMove", []),
	Signature("playerTurn", "PlayerTurn", []),
	Signature("setEnvelope", "SetEnvelope", ["eval", "eval", "eval", "eval", "eval", "eval"]),
	Signature("turnTowardPlayerX", "TurnTowardPlayerX", ["eval"]),
	Signature("turnTowardPlayerY", "TurnTowardPlayerY", ["eval"]),
	Signature("turnTowardPlayerXY", "TurnTowardPlayerXY", ["eval", "eval"]),
	Signature("forceDoor", "ForceDoor", ["eval"]),
	Signature("levelStats", "LevelStats", []),
	Signature("reSeed", "ReSeed", []),
	Signature("showBonusOn", "ShowBonusOn", []),
	Signature("showBonusOff", "ShowBonusOff", []),
	Signature("removeModel", "RemoveModel", []),
	Signature("quickPlayer", "QuickPlayer", []),
	Signature("gobboON", "GobboON", []),
	Signature("gobboOFF", "GobboOFF", []),
	Signature("unActivated", "UnActivated", []),
	Signature("endSubLevel", "EndSubLevel", []),
	Signature("turnOffLookAtMe", "TurnOffLookAtMe", []),
	Signature("heightFloat", "HeightFloat", []),
	Signature("flashOn", "FlashOn", []),
	Signature("flashOff", "FlashOff", []),
	Signature("_light_0xd4", "_Light_0xd4", ["eval"]),
	Signature("_light_0xd5", "_Light_0xd5", ["eval"]),
	Signature("_light_0xd6", "_Light_0xd6", ["eval", "eval", "eval"]),
	Signature("commandError", "CommandError", []),
	Signature("command0xfd", "Command0xfd", []),
	Signature("tonyTest", "TonyTest", []),
	Signature("lewisTest", "LewisTest", ["int8", "eval"]),
]
COMMAND_MAP = {sign.name: sign for sign in COMMAND_SIGNATURES}

FUNCTION_SIGNATURES = [
    Signature("loadObject", "LoadObject", ["string"]),
    Signature("loadAsset0", "LoadAsset0", ["string"]),
    Signature("loadAsset1", "LoadAsset1", ["string"]),
    Signature("loadAsset2", "LoadAsset2", ["string"]),
    Signature("loadAsset3", "LoadAsset3", ["string"]),
    Signature("loadAsset4", "LoadAsset4", []),
    Signature("loadAsset5", "LoadAsset5", []),
    Signature("loadAnim", "LoadAnim", ["string"]),
    Signature("loadSound", "LoadSound", ["int8", "varargs"]),

    Signature("sin", "Sine", ["stack"]),
    Signature("cos", "Cosine", ["stack"]),
	Signature("sqrt", "SquareRoot", ["stack"]),
	Signature("abs", "AbsoluteValue", ["stack"]),
    Signature("random", "RandomNumber", ["stack"]),
    Signature("floor", "FloorNumber", ["stack"]),

    Signature("bitAnd", "BitAnd", ["stack", "stack"]),
    
	Signature("distanceFromPoint", "DistanceFromPoint", ["stack", "stack", "stack"]),
    Signature("checkAnimFlag32", "CheckAnimFlag32", ["stack", "stack"]),
]
FUNCTION_MAP = {sign.name: sign for sign in FUNCTION_SIGNATURES}

BINARY_OPERATOR_MAP = {
    "and": "TopPairNotZero",
    "or": "BitOr",
    "xor": "NotEqual",
    ">": "TopLess",
    "<": "TopGreater",
    ">=": "TopNotGreater",
    "<=": "TopNotLess",
    "==": "Equal",
    "!=": "NotEqual",
    "+": "Add",
	"-": "Subtract",
    "*": "Multiply",
    "/": "Divide",
    ">>": "BitShiftRight",
    "<<": "BitShiftLeft"
}

UNARY_OPERATOR_MAP = {
    "!": "IsZero",
    "+": None,
    "-": "Negate"
}

VAR_MAP = {
    "vars": {"let": "LetGVar", "push": "PushGVar", "limit": 192, "kind_int": 2, "name_pfx": "g_var"},
    "pg_vars": {"let": "LetPGVar", "push": "PushPGVar", "limit": 192, "kind_int": None, "name_pfx": "pg_var"},
    "alien_vars": {"let": "LetAVar", "push": "PushAVar", "limit": 128, "kind_int": None, "name_pfx": "a_var"}, # not sure about limit
    "params": {"let": "LetParam", "push": "PushStratVar", "limit": 8, "kind_int": 29, "name_pfx": "param"},
    "xg_vars": {"let": "LetXGVar", "push": "PushExternGlobal", "limit": 74, "kind_int": None, "name_pfx": "xg_var"},
    "x_params": {"let": "LetXParam", "push": "PushXParam", "limit": 8, "kind_int": None, "name_pfx": "x_param"}
}
VAR_SETTERS = [v["let"] for v in VAR_MAP.values()]
VAR_GETTERS = [v["push"] for v in VAR_MAP.values()]

VAR_SIZES = [
    {"index": 0, "name": "S", "size": 0},
    {"index": 1, "name": "M", "size": 4},
    {"index": 2, "name": "L", "size": 8},
    {"index": 3, "name": "XL", "size": 16},
    {"index": 4, "name": "XXL", "size": 32},
    {"index": 5, "name": "XXXL", "size": 64},
    {"index": 6, "name": "SXXXL", "size": 192}
]

SPECIAL_CONDITIONS = {
    "animend": "IfAnimend",
    "jumping": "IfJumping",
    "falling": "IfFalling",
}

ALIEN_VARS = {
    "a_var28": "distance_to_player",
    "a_var29": "distance_to_init_pos"
}
